SELECT
    E.CODCFO, E.NOME AS RAZAO, E.CGCCFO AS CNPJCPF, E.NOMEFANTASIA, 
    /*E.PAGREC,*/ 
    CASE WHEN E.PAGREC = 1 THEN 'SIM'END AS CLIENTE,
    CASE WHEN E.PAGREC = 2 THEN 'NÃO'END AS FORNECEDOR,
    /*CASE WHEN E.PAGREC = 3 THEN 'AMBOS'END AS AMBOS,*/
    '' AS TRANSPORTADORA,
    '' AS FUNCIONARIO,
    E.CONTATO, E.RUA AS ENDERECO, E.NUMERO, E.BAIRRO, E.COMPLEMENTO, E.CODETD AS ESTADO, 
    E.CIDADE, E.PAIS, E.CEP,
    '' AS DDD,
    E.TELEFONE,
    '' AS DDD2,
    E.TELEX AS CELULAR,
    '' AS DDD3,
    E.FAX, 
    E.EMAIL, 
    '' AS WEBSITE, 
    CONTA.DESCRICAO AS BANCO,
    CASE 
    WHEN CONTA.DIGITOAGENCIA IS NOT NULL THEN CONTA.CODIGOAGENCIA || '-' || CONTA.DIGITOAGENCIA
    ELSE CONTA.CODIGOAGENCIA 
    END AS AGENCIA, 
    CASE 
    WHEN CONTA.DIGITOCONTA IS NOT NULL THEN CONTA.CONTACORRENTE || '-' || CONTA.DIGITOCONTA
    ELSE CONTA.CONTACORRENTE 
    END AS CONTA,
    CONTA.CGCFAVORECIDO AS CNPJCPFFAVORECIDO,
    CONTA.FAVORECIDO AS TITULAR,
    '' AS TRANSFERENCIA,
    E.INSCRESTADUAL, E.INSCRMUNICIPAL, E.SUFRAMA, 
    CASE 
        WHEN E.RAMOATIV = 1 THEN 'COMERCIO'
        WHEN E.RAMOATIV = 2 THEN 'INDUSTRIA'
        WHEN E.RAMOATIV = 4 THEN 'SERVICO'
        WHEN E.RAMOATIV = 8 THEN 'ASSOCIACAO'
        WHEN E.RAMOATIV = 16 THEN 'RURAL'
        ELSE '0' -- SEM ATIVIDADE MARCADO NA FLAG 
    END AS RAMOATIVIDADE,
    '' AS CNAE,
    CASE 
        WHEN E.CONTRIBUINTE = 1 THEN 'SIM'
        WHEN E.CONTRIBUINTE = 2 THEN 'NAO'
        WHEN E.CONTRIBUINTE = 0 THEN 'NAO'
        END AS CONTRIBUINTE
    /*CONTA.CHAVE AS PIX
    COUNT() OVER() AS TOTAL_LINHAS/
FROM FCFO E
LEFT JOIN FDADOSPGTO CONTA ON E.CODCOLIGADA = CONTA.CODCOLCFO AND E.CODCFO = CONTA.CODCFO 
WHERE E.CODCFO = 'A089158' /AND CONTA.CODCOLIGADA = '15'/
--CONTA.CONTACORRENTE IS NOT NULL */ 
/*WHERE E.PAGREC = 2 AND E.CODCFO ='A134412'*/
ORDER BY CONTA.CONTACORRENTE,CONTA.CODIGOAGENCIA;